[functions]
  external_node_modules = ["express", "multer", "csv-parse", "xlsx", "winston"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"